spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/shiro
      username: root
      password: root
#  data:
#    mongodb:
#      database: test
#      host: 127.0.0.1
#      port: 27017
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
